[package]
name = "imvi"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "0.13.1", features = ["macros"] }
sdl3 = { version = "0.16.2", features = ["build-from-source", "image"] }
